---
version: "3.7"
services:
   web-server:
      image: nginx:latest
      ports:
         - "8000:80"
      volumes:
         - ./docker/config/nginx/conf.d:/etc/nginx/conf.d
      depends_on:
         - wsgi
      networks:
         - nginx_network
   wsgi:
      build:
         dockerfile: docker/config/wsgi/py.Dockerfile
         context: .
      restart: always
      env_file:
         - ./docker/config/wsgi/.env
      depends_on:
         - database
      networks:
         - nginx_network
   database:
      image: postgres:latest
      restart: always
      env_file:
         - ./docker/config/database/.env
      volumes:
         - database-data:/var/lib/postgresql/data
      networks:
         - nginx_network
volumes:
   database-data:

networks:
   nginx_network:
      driver: bridge
